observations_short_map = {
    'A great deal of time is spent in activities necessary to obtain the opioid  use the opioid  or recover from its effects': 'OpioidTimeSpent',
    'ALT (Elevated)': 'ALTElevated',
    'AST (Elevated)': 'ASTElevated',
    'Abuse Status [OMAHA]': 'AbuseStatus',
    'Activated clotting time (ACT) of Blood by Coagulation assay': 'ACT',
    'Address': 'Address',
    'Adenovirus A+B+C+D+E DNA [Presence] in Respiratory specimen by NAA with probe detection': 'AdenovirusPresence',
    'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma': 'ALT',
    'Albumin': 'Albumin',
    'Albumin [Mass/volume] in Serum or Plasma': 'AlbuminMass',
    'Alkaline Phosphatase': 'AlkPhos',
    'Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma': 'AlkPhosActivity',
    'American house dust mite IgE Ab [Units/volume] in Serum': 'DustMiteIgE',
    'Anion Gap': 'AnionGap',
    'Appearance of Urine': 'UrineAppearance',
    'Are you a refugee?': 'RefugeeStatus',
    'Are you covered by health insurance or some other kind of health care plan [PhenX]': 'InsuranceCoverage',
    'Are you worried about losing your housing?': 'HousingConcern',
    'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma': 'AST',
    'At any point in the past 2 years  has season or migrant farm work been your or your family\'s main source of income?': 'MigrantFarmWork',
    'Bacteria': 'Bacteria',
    'Bacteria identified in Urine by Culture': 'UrineBacteria',
    'Basophils [#/volume] in Blood by Automated count': 'BasophilCount',
    'Basophils/100 leukocytes in Blood by Automated count': 'BasophilPercent',
    'Bicarbonate [Moles/volume] in Arterial blood': 'ArterialBicarb',
    'Bicarbonate [Moles/volume] in Venous blood': 'VenousBicarb',
    'Bilirubin.total [Mass/volume] in Serum or Plasma': 'TotalBilirubin',
    'Bilirubin.total [Mass/volume] in Urine by Test strip': 'UrineBilirubinMass',
    'Bilirubin.total [Presence] in Urine by Test strip': 'UrineBilirubinPresence',
    'Body Height': 'Height',
    'Body Temperature': 'Temperature',
    'Body Weight': 'Weight',
    'Body mass index (BMI) [Percentile] Per age and sex': 'BMIPercentile',
    'Body mass index (BMI) [Ratio]': 'BMI',
    'Body temperature': 'BodyTemp',
    'C reactive protein [Mass/volume] in Serum or Plasma': 'CRP',
    'CD3+CD4+ (T4 helper) cells [#/volume] in Blood': 'CD4Count',
    'Calcium': 'Calcium',
    'Calcium [Mass/volume] in Blood': 'BloodCalcium',
    'Calcium [Mass/volume] in Serum or Plasma': 'SerumCalcium',
    'Capillary refill [Time] of Nail bed': 'CapRefill',
    'Carbon Dioxide': 'CO2',
    'Carbon dioxide  total [Moles/volume] in Blood': 'TotalCO2Blood',
    'Carbon dioxide  total [Moles/volume] in Serum or Plasma': 'TotalCO2Serum',
    'Carbon dioxide  total [Moles/volume] in Venous blood': 'TotalCO2Venous',
    'Carbon dioxide [Partial pressure] in Arterial blood': 'PCO2Arterial',
    'Carbon dioxide [Partial pressure] in Venous blood': 'PCO2Venous',
    'Casts': 'Casts',
    'Cat dander IgE Ab [Units/volume] in Serum': 'CatIgE',
    'Cause of Death [US Standard Certificate of Death]': 'DeathCause',
    'Chloride': 'Chloride',
    'Chloride [Moles/volume] in Blood': 'BloodChloride',
    'Chloride [Moles/volume] in Serum or Plasma': 'SerumChloride',
    'Cholesterol [Mass/volume] in Serum or Plasma': 'TotalCholesterol',
    'Cholesterol in HDL [Mass/volume] in Serum or Plasma': 'HDL',
    'Choriogonadotropin (pregnancy test) [Presence] in Urine': 'PregnancyTest',
    'Cladosporium herbarum IgE Ab [Units/volume] in Serum': 'MoldIgE',
    'Clarity of Urine': 'UrineClarity',
    'Codfish IgE Ab [Units/volume] in Serum': 'CodfishIgE',
    'Color of Urine': 'UrineColor',
    'Common Ragweed IgE Ab [Units/volume] in Serum': 'RagweedIgE',
    'Continued opioid use despite having persistent or recurrent social or interpersonal problems caused or exacerbated by the effects of opioids': 'OpioidSocialProblems',
    'Continued use despite knowledge of having a persistent or recurrent physical or psychological problem that is likely to have been caused or exacerbated by opioids.': 'OpioidDespiteProblems',
    'Cow milk IgE Ab [Units/volume] in Serum': 'MilkIgE',
    'Craving or a strong desire to use opioids': 'OpioidCraving',
    'Creatine kinase [Enzymatic activity/volume] in Serum or Plasma': 'CK',
    'Creatinine': 'Creatinine',
    'Creatinine [Mass/volume] in Blood': 'BloodCreatinine',
    'Creatinine [Mass/volume] in Serum or Plasma': 'SerumCreatinine',
    'DALY': 'DALY',
    'DXA Radius and Ulna [T-score] Bone density': 'ForearmBoneDensity',
    'Diastolic Blood Pressure': 'DBP',
    'Distant metastases.clinical [Class] Cancer': 'DistantMetastases',
    'Do you consider yourself Hispanic/Latino?': 'HispanicStatus',
    'Do you feel physically and emotionally safe where you currently live?': 'SafetyStatus',
    'Drugs of abuse 5 panel - Urine by Screen method': 'DrugScreen',
    'Egg white IgE Ab [Units/volume] in Serum': 'EggIgE',
    'Emergency severity index': 'ESI',
    'Employment status - current': 'EmploymentStatus',
    'Eosinophils [#/volume] in Blood by Automated count': 'EosinophilCount',
    'Eosinophils/100 leukocytes in Blood by Automated count': 'EosinophilPercent',
    'Epithelial Cells': 'EpithelialCells',
    'Erythrocyte distribution width [Entitic volume] by Automated count': 'RDWv',
    'Erythrocyte distribution width [Ratio] by Automated count': 'RDW',
    'Erythrocytes [#/volume] in Blood': 'RBCCount',
    'Erythrocytes [#/volume] in Blood by Automated count': 'AutoRBCCount',
    'Estrogen receptor Ag [Presence] in Breast cancer specimen by Immune stain': 'ER',
    'Estrogen+Progesterone receptor Ag [Presence] in Tissue by Immune stain': 'ER/PR',
    'Exercise stress test study': 'StressTest',
    'FEV1/FVC': 'FEV1/FVC',
    'Fall risk level [Morse Fall Scale]': 'FallRiskLevel',
    'Fall risk total [Morse Fall Scale]': 'FallRiskTotal',
    'Ferritin [Mass/volume] in Serum or Plasma': 'Ferritin',
    'Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma': 'DDimer',
    'Functional capacity NYHA': 'NYHAClass',
    'Generalized anxiety disorder 7 item (GAD-7) total score [Reported.PHQ]': 'GAD7',
    'Globulin': 'Globulin',
    'Globulin [Mass/volume] in Serum by calculation': 'SerumGlobulin',
    'Glomerular filtration rate/1.73 sq M.predicted': 'GFR',
    'Glomerular filtration rate/1.73 sq M.predicted [Volume Rate/Area] in Serum or Plasma by Creatinine-based formula (MDRD)': 'MDRDGFR',
    'Glucose': 'Glucose',
    'Glucose [Mass/volume] in Blood': 'BloodGlucose',
    'Glucose [Mass/volume] in Serum or Plasma': 'SerumGlucose',
    'Glucose [Mass/volume] in Urine by Test strip': 'UrineGlucoseMass',
    'Glucose [Presence] in Urine by Test strip': 'UrineGlucosePresence',
    'Gram positive blood culture panel by Probe in Positive blood culture': 'GramPosBloodCulture',
    'HER2 [Presence] in Breast cancer specimen by FISH': 'HER2FISH',
    'HER2 [Presence] in Breast cancer specimen by Immune stain': 'HER2IHC',
    'HIV 1 Ab [Presence] in Serum': 'HIVAb',
    'HIV 1 RNA [#/volume] (viral load) in Serum or Plasma by NAA with probe detection': 'HIVViralLoad',
    'HIV status': 'HIVStatus',
    'Has lack of transportation kept you from medical appointments  meetings  work  or from getting things needed for daily living': 'TransportationBarrier',
    'Have you been discharged from the armed forces of the United States?': 'VeteranStatus',
    'Head Occipital-frontal circumference': 'HeadCircumference',
    'Head Occipital-frontal circumference Percentile': 'HeadCircumferencePercentile',
    'Heart rate': 'HR',
    'Hematocrit': 'Hct',
    'Hematocrit [Volume Fraction] of Blood': 'BloodHct',
    'Hematocrit [Volume Fraction] of Blood by Automated count': 'AutoHct',
    'Hemoglobin': 'Hgb',
    'Hemoglobin A1c/Hemoglobin.total in Blood': 'HbA1c',
    'Hemoglobin [Mass/volume] in Blood': 'BloodHgb',
    'Hemoglobin [Presence] in Urine by Test strip': 'UrineHgb',
    'Hemoglobin.gastrointestinal.lower [Presence] in Stool by Immunoassay --1st specimen': 'StoolOccultBlood',
    'Highest level of education': 'EducationLevel',
    'History of Hospitalizations+Outpatient visits Narrative': 'MedicalHistory',
    'Honey bee IgE Ab [Units/volume] in Serum': 'BeeIgE',
    'Housing status': 'HousingStatus',
    'How many people are living or staying at this address?': 'HouseholdSize',
    'How often do you see or talk to people that you care about and feel close to (For example: talking to friends on the phone  visiting friends or family  going to church or club meetings)?': 'SocialConnections',
    'Human metapneumovirus RNA [Presence] in Respiratory specimen by NAA with probe detection': 'hMPV',
    'INR in Platelet poor plasma by Coagulation assay': 'INR',
    'Important social  occupational  or recreational activities are given up or reduced because of opioid use': 'OpioidActivitiesReducedDue',
    'In the past year  have you or any family members you live with been unable to get any of the following when it was really needed?': 'ResourceNeeds',
    'In the past year  have you spent more than 2 nights in a row in a jail  prison  detention center  or juvenile correctional facility?': 'Incarceration',
    'Influenza virus A Ag [Presence] in Upper respiratory specimen by Rapid immunoassay': 'FluA',
    'Influenza virus A RNA [Presence] in Respiratory specimen by NAA with probe detection': 'FluA_PCR',
    'Influenza virus B Ag [Presence] in Upper respiratory specimen by Rapid immunoassay': 'FluB',
    'Influenza virus B RNA [Presence] in Respiratory specimen by NAA with probe detection': 'FluB_PCR',
    'Iron [Mass/volume] in Serum or Plasma': 'Iron',
    'Iron binding capacity [Mass/volume] in Serum or Plasma': 'TIBC',
    'Iron saturation [Mass Fraction] in Serum or Plasma': 'IronSat',
    'Ketones [Mass/volume] in Urine by Test strip': 'UrineKetonesMass',
    'Ketones [Presence] in Urine by Test strip': 'UrineKetonesPresence',
    'Lactate [Moles/volume] in Blood': 'Lactate',
    'Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Lactate to pyruvate reaction': 'LDH',
    'Latex IgE Ab [Units/volume] in Serum': 'LatexIgE',
    'Left ventricular Ejection fraction': 'LVEF',
    'Leukocyte esterase [Presence] in Urine by Test strip': 'LeukEsterase',
    'Leukocytes [#/volume] in Blood': 'WBCCount',
    'Leukocytes [#/volume] in Blood by Automated count': 'AutoWBCCount',
    'Low Density Lipoprotein Cholesterol': 'LDL',
    'Lymph nodes with isolated tumor cells [#] in Cancer specimen by Light microscopy': 'ITCNodes',
    'Lymph nodes with macrometastases [#] in Cancer specimen by Light microscopy': 'MacroNodes',
    'Lymph nodes with micrometastases [#] in Cancer specimen by Light microscopy': 'MicroNodes',
    'Lymphocytes [#/volume] in Blood by Automated count': 'LymphCount',
    'Lymphocytes/100 leukocytes in Blood by Automated count': 'LymphPercent',
    'MCH [Entitic mass] by Automated count': 'MCH',
    'MCHC [Mass/volume] by Automated count': 'MCHC',
    'MCV': 'MCV',
    'MCV [Entitic volume] by Automated count': 'AutoMCV',
    'Magnesium [Mass/volume] in Blood': 'BloodMagnesium',
    'Magnesium [Mass/volume] in Serum or Plasma': 'SerumMagnesium',
    'Mean blood pressure': 'MAP',
    'Medication management note': 'MedNote',
    'Microalbumin/Creatinine [Mass Ratio] in Urine': 'UACR',
    'Monocytes [#/volume] in Blood by Automated count': 'MonocyteCount',
    'Monocytes/100 leukocytes in Blood by Automated count': 'MonocytePercent',
    'Mucus Threads': 'MucusThreads',
    'NT-proBNP': 'NTproBNP',
    'Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Blood by Immunoassay': 'BNP',
    'Neutrophils [#/volume] in Blood by Automated count': 'NeutrophilCount',
    'Neutrophils/100 leukocytes in Blood by Automated count': 'NeutrophilPercent',
    'Nitrite [Presence] in Urine by Test strip': 'UrineNitrite',
    'Objective assessment of cardiovascular disease NYHA': 'NYHAAssessment',
    'Odor of Urine': 'UrineOdor',
    'Operative Status Value': 'OpStatus',
    'Opioids are often taken in larger amounts or over a longer period than was intended': 'OpioidExcessiveUse',
    'Overall summary score [KCCQ-12]': 'KCCQ12',
    'Oxygen [Partial pressure] in Arterial blood': 'PaO2',
    'Oxygen [Partial pressure] in Venous blood': 'PvO2',
    'Oxygen saturation in Arterial blood': 'SaO2',
    'Oxygen/Total gas setting [Volume Fraction] Ventilator': 'FiO2',
    'Pain severity - 0-10 verbal numeric rating [Score] - Reported': 'PainScore',
    'Pain severity - Reported': 'PainLevel',
    'Pain severity in the past week - 0-10 numeric rating [Reported]': 'WeeklyPainScore',
    'Parainfluenza virus 1 RNA [Presence] in Respiratory specimen by NAA with probe detection': 'PIV1',
    'Parainfluenza virus 2 RNA [Presence] in Respiratory specimen by NAA with probe detection': 'PIV2',
    'Parainfluenza virus 3 RNA [Presence] in Respiratory specimen by NAA with probe detection': 'PIV3',
    'Patient Health Questionnaire 2 item (PHQ-2) total score [Reported]': 'PHQ2',
    'Patient Health Questionnaire 9 item (PHQ-9) total score [Reported]': 'PHQ9',
    'Patient Health Questionnaire-9: Modified for Teens total score [Reported.PHQ.Teen]': 'PHQ9Teen',
    'Peanut IgE Ab [Units/volume] in Serum': 'PeanutIgE',
    'Percentage area affected by eczema Head and Neck [PhenX]': 'EczemaHeadNeck',
    'Percentage area affected by eczema Lower extremity - bilateral [PhenX]': 'EczemaLowerExt',
    'Percentage area affected by eczema Trunk [PhenX]': 'EczemaTrunk',
    'Percentage area affected by eczema Upper extremity - bilateral [PhenX]': 'EczemaUpperExt',
    'Phosphate [Mass/volume] in Serum or Plasma': 'Phosphate',
    'Physical findings of Abdomen by Palpation': 'AbdExam',
    'Physical findings of Prostate': 'ProstateExam',
    'Platelet Count': 'Platelets',
    'Platelet distribution width [Entitic volume] in Blood by Automated count': 'PDW',
    'Platelet mean volume [Entitic volume] in Blood by Automated count': 'MPV',
    'Platelets [#/volume] in Blood by Automated count': 'PlateletCount',
    'Polyp size greatest dimension': 'PolypSize',
    'Potassium': 'K',
    'Potassium [Moles/volume] in Blood': 'BloodK',
    'Potassium [Moles/volume] in Serum or Plasma': 'SerumK',
    'Preferred language': 'Language',
    'Primary insurance': 'Insurance',
    'Primary tumor.clinical [Class] Cancer': 'TumorClass',
    'Priority Level': 'Priority',
    'Procalcitonin [Mass/volume] in Serum or Plasma': 'PCT',
    'Procedure Narrative': 'ProcedureNote',
    'Progesterone receptor Ag [Presence] in Breast cancer specimen by Immune stain': 'PR',
    'Prostate specific Ag [Mass/volume] in Serum or Plasma': 'PSA',
    'Protein': 'Protein',
    'Protein [Mass/volume] in Serum or Plasma': 'SerumProtein',
    'Protein [Mass/volume] in Urine by Test strip': 'UrineProteinMass',
    'Protein [Presence] in Urine by Test strip': 'UrineProteinPresence',
    'Prothrombin time (PT)': 'PT',
    'QALY': 'QALY',
    'QOLS': 'QOLS',
    'RBC Distribution Width': 'RDWPercent',
    'RBCs': 'RBCs',
    'Race': 'Race',
    'Recurrent opioid use in situations in which it is physically hazardous': 'OpioidHazardousUse',
    'Recurrent opioid use resulting in a failure to fulfill major role obligations at work  school  or home': 'OpioidObligationFailure',
    'Regional lymph nodes.clinical [Class] Cancer': 'LymphNodeClass',
    'Respiratory rate': 'RR',
    'Respiratory syncytial virus RNA [Presence] in Respiratory specimen by NAA with probe detection': 'RSV',
    'Response to cancer treatment': 'TreatmentResponse',
    'Rhinovirus RNA [Presence] in Respiratory specimen by NAA with probe detection': 'Rhinovirus',
    'SARS-CoV-2 RNA Pnl Resp NAA+probe': 'COVID19',
    'Sexual orientation': 'SexOrientation',
    'Shrimp IgE Ab [Units/volume] in Serum': 'ShrimpIgE',
    'Site of distant metastasis in Breast tumor': 'MetSite',
    'Size.maximum dimension in Tumor': 'TumorSize',
    'Sodium': 'Na',
    'Sodium [Moles/volume] in Blood': 'BloodNa',
    'Sodium [Moles/volume] in Serum or Plasma': 'SerumNa',
    'Soybean IgE Ab [Units/volume] in Serum': 'SoyIgE',
    'Specific gravity of Urine by Test strip': 'UrineSpGr',
    'Stage group.clinical Cancer': 'CancerStage',
    'Stress level': 'StressLevel',
    'Symptom': 'Symptom',
    'Systolic Blood Pressure': 'SBP',
    'There is a persistent desire or unsuccessful efforts to cut down or control opioid use': 'OpioidControlFailure',
    'Thyrotropin [Units/volume] in Serum or Plasma': 'TSH',
    'Thyroxine (T4) free [Mass/volume] in Serum or Plasma': 'FT4',
    'Tobacco smoking status': 'SmokingStatus',
    'Tolerance as defined by either of the following: a) Need for markedly increased amounts of opioids to achieve intoxication or desired effect b) Markedly diminished effect with continued use of the same amount of opioid': 'OpioidTolerance',
    'Total Bilirubin (Elevated)': 'BilirubinElevated',
    'Total score [AUDIT-C]': 'AUDITC',
    'Total score [DAST-10]': 'DAST10',
    'Total score [HARK]': 'HARK',
    'Total score [MMSE]': 'MMSE',
    'Treatment status Cancer': 'CancerTxStatus',
    'Triglycerides': 'TG',
    'Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method': 'hsTnI',
    'US Guidance for biopsy of Prostate': 'ProstateUSBiopsy',
    'Urea Nitrogen': 'BUN',
    'Urea nitrogen [Mass/volume] in Blood': 'BloodBUN',
    'Urea nitrogen [Mass/volume] in Serum or Plasma': 'SerumBUN',
    'VR-12 Bodily pain (BP) score - oblique method': 'VR12Pain',
    'VR-12 General health (GH) score - oblique method': 'VR12Health',
    'VR-12 Mental health (MH) score - oblique method': 'VR12Mental',
    'VR-12 Physical functioning (PF) score - oblique method': 'VR12Physical',
    'VR-12 Role emotion (RE) score - oblique method': 'VR12Emotion',
    'VR-12 Role physical (RP) score - oblique method': 'VR12RolePhys',
    'VR-12 Social functioning (SF) score - oblique method': 'VR12Social',
    'VR-12 Vitality (VT) score - oblique method': 'VR12Vitality',
    'WBCs': 'WBCs',
    'Walnut IgE Ab [Units/volume] in Serum': 'WalnutIgE',
    'Weight difference [Mass difference] --pre dialysis - post dialysis': 'DialysisWtLoss',
    'Weight-for-length Per age and sex': 'WtForLength',
    'What number best describes how pain has interfered with your enjoyment of life during the past week': 'PainEnjoyment',
    'What number best describes how pain has interfered with your general activity during the past week': 'PainActivity',
    'What was your best estimate of the total income of all family members from all sources  before taxes  in last year?': 'HouseholdIncome',
    'Wheat IgE Ab [Units/volume] in Serum': 'WheatIgE',
    'White oak IgE Ab [Units/volume] in Serum': 'OakIgE',
    'Withdrawal * as manifested by either of the following: a) Characteristic opioid withdrawal syndrome b) Same (or a closely related) substance is taken to relieve or avoid withdrawal symptoms': 'OpioidWithdrawal',
    'Within the last year  have you been afraid of your partner or ex-partner?': 'PartnerFear',
    'aPTT in Blood by Coagulation assay': 'aPTT',
    'pH of Arterial blood': 'ArterialPH',
    'pH of Urine by Test strip': 'UrinePH',
    'pH of Venous blood': 'VenousPH'
}

medications_short_map = {
    '0.25 ML Leuprolide Acetate 30 MG/ML Prefilled Syringe': '0.25ml Leuprolide Acet 30mg/ml PFS',
    '0.4 ML Enoxaparin sodium 100 MG/ML Prefilled Syringe': '0.4ml Enoxaparin Na 100mg/ml PFS',
    '1 ML DOCEtaxel 20 MG/ML Injection': '1ml Docetaxel 20mg/ml inj',
    '1 ML Enoxaparin sodium 150 MG/ML Prefilled Syringe': '1ml Enoxaparin Na 150mg/ml PFS',
    '1 ML Epoetin Alfa 4000 UNT/ML Injection [Epogen]': '1ml Epoetin 4000u/ml inj (Epogen)',
    '1 ML Morphine Sulfate 5 MG/ML Injection': '1ml Morphine 5mg/ml inj',
    '1 ML Vasopressin (USP) 20 UNT/ML Injection': '1ml Vasopressin 20u/ml inj',
    '1 ML heparin sodium  porcine 5000 UNT/ML Injection': '1ml Heparin Na 5000u/ml inj',
    '1 ML medroxyPROGESTERone acetate 150 MG/ML Injection': '1ml MPA 150mg/ml inj',
    '1 ML medroxyprogesterone acetate 150 MG/ML Injection': '1ml MPA 150mg/ml inj',
    '1 ML tacrolimus 5 MG/ML Injection': '1ml Tacrolimus 5mg/ml inj',
    '10 ML Alfentanil 0.5 MG/ML Injection': '10ml Alfentanil 0.5mg/ml inj',
    '10 ML Doxorubicin Hydrochloride 2 MG/ML Injection': '10ml Doxorubicin 2mg/ml inj',
    '10 ML Fentanyl 0.05 MG/ML Injection': '10ml Fentanyl 0.05mg/ml inj',
    '10 ML Fluorouracil 50 MG/ML Injection': '10ml 5-FU 50mg/ml inj',
    '10 ML Furosemide 10 MG/ML Injection': '10ml Lasix 10mg/ml inj',
    '10 ML oxaliplatin 5 MG/ML Injection': '10ml Oxaliplatin 5mg/ml inj',
    '100 ML Epirubicin Hydrochloride 2 MG/ML Injection': '100ml Epirubicin 2mg/ml inj',
    '100 ML Propofol 10 MG/ML Injection': '100ml Propofol 10mg/ml inj',
    '100 ML eptifibatide 0.75 MG/ML Injection': '100ml Eptifibatide 0.75mg/ml inj',
    '100 ML tirofiban 0.05 MG/ML Injection': '100ml Tirofiban 0.05mg/ml inj',
    '12 HR Hydrocodone Bitartrate 10 MG Extended Release Oral Capsule': '12hr Hydrocodone 10mg ER cap',
    '120 ACTUAT fluticasone propionate 0.044 MG/ACTUAT Metered Dose Inhaler [Flovent]': '120act Fluticasone 0.044mg/act MDI (Flovent)',
    '120 ACTUAT fluticasone propionate 0.11 MG/ACTUAT Metered Dose Inhaler [Flovent]': '120act Fluticasone 0.11mg/act MDI (Flovent)',
    '150 ML vancomycin 5 MG/ML Injection': '150ml Vancomycin 5mg/ml inj',
    '168 HR Ethinyl Estradiol 0.00146 MG/HR / norelgestromin 0.00625 MG/HR Transdermal System': '168hr EE 0.00146mg/hr+Norelgestromin 0.00625mg/hr patch',
    '2 ML Ondansetron 2 MG/ML Injection': '2ml Ondansetron 2mg/ml inj',
    '2 ML morphine sulfate 1 MG/ML Injection': '2ml Morphine 1mg/ml inj',
    '24 HR Donepezil hydrochloride 10 MG / Memantine hydrochloride 28 MG Extended Release Oral Capsule': '24hr Donepezil 10mg+Memantine 28mg ER cap',
    '24 HR Metformin hydrochloride 500 MG Extended Release Oral Tablet': '24hr Metformin 500mg ER tab',
    '24 HR carvedilol phosphate 20 MG Extended Release Oral Capsule [Coreg]': '24hr Carvedilol 20mg ER cap (Coreg)',
    '24 HR metoprolol succinate 100 MG Extended Release Oral Tablet': '24hr Metoprolol 100mg ER tab',
    '24 HR metoprolol succinate 200 MG Extended Release Oral Tablet': '24hr Metoprolol 200mg ER tab',
    '24 HR metoprolol succinate 25 MG Extended Release Oral Tablet': '24hr Metoprolol 25mg ER tab',
    '24 HR metoprolol succinate 50 MG Extended Release Oral Tablet': '24hr Metoprolol 50mg ER tab',
    '24 HR propranolol hydrochloride 60 MG Extended Release Oral Capsule': '24hr Propranolol 60mg ER cap',
    '24 HR tacrolimus 1 MG Extended Release Oral Tablet': '24hr Tacrolimus 1mg ER tab',
    '24 HR tacrolimus 5 MG Extended Release Oral Capsule': '24hr Tacrolimus 5mg ER cap',
    '25 ML protamine sulfate (USP) 10 MG/ML Injection': '25ml Protamine 10mg/ml inj',
    '3 ML liraglutide 6 MG/ML Pen Injector': '3ml Liraglutide 6mg/ml pen',
    '4 ML Norepinephrine 1 MG/ML Injection': '4ml Norepinephrine 1mg/ml inj',
    '4 ML norepinephrine 1 MG/ML Injection': '4ml Norepinephrine 1mg/ml inj',
    '5 ML SUFentanil 0.05 MG/ML Injection': '5ml Sufentanil 0.05mg/ml inj',
    '5 ML fulvestrant 50 MG/ML Prefilled Syringe': '5ml Fulvestrant 50mg/ml PFS',
    '5 ML hyaluronidase-oysk 2000 UNT/ML / trastuzumab 120 MG/ML Injection': '5ml Hyaluronidase 2000u/ml+Trastuzumab 120mg/ml inj',
    '60 ACTUAT Fluticasone propionate 0.25 MG/ACTUAT / salmeterol 0.05 MG/ACTUAT Dry Powder Inhaler': '60act Fluticasone 0.25mg/Salmeterol 0.05mg DPI',
    '72 HR Fentanyl 0.025 MG/HR Transdermal System': '72hr Fentanyl 0.025mg/hr patch',
    'Abuse-Deterrent 12 HR Oxycodone Hydrochloride 10 MG Extended Release Oral Tablet [Oxycontin]': 'AD 12hr Oxycodone 10mg ER tab (Oxycontin)',
    'Abuse-Deterrent 12 HR Oxycodone Hydrochloride 15 MG Extended Release Oral Tablet': 'AD 12hr Oxycodone 15mg ER tab',
    'Acetaminophen 160 MG Chewable Tablet': 'APAP 160mg chew tab',
    'Acetaminophen 21.7 MG/ML / Dextromethorphan Hydrobromide 1 MG/ML / doxylamine succinate 0.417 MG/ML Oral Solution': 'APAP 21.7mg/DM 1mg/Doxylamine 0.417mg per ml soln',
    'Acetaminophen 300 MG / Codeine Phosphate 15 MG Oral Tablet': 'APAP 300mg/Codeine 15mg tab',
    'Acetaminophen 300 MG / HYDROcodone Bitartrate 5 MG Oral Tablet': 'APAP 300mg/Hydrocodone 5mg tab',
    'Acetaminophen 300 MG / Hydrocodone Bitartrate 5 MG Oral Tablet': 'APAP 300mg/Hydrocodone 5mg tab',
    'Acetaminophen 325 MG / HYDROcodone Bitartrate 7.5 MG Oral Tablet': 'APAP 325mg/Hydrocodone 7.5mg tab',
    'Acetaminophen 325 MG / Oxycodone Hydrochloride 10 MG Oral Tablet [Percocet]': 'APAP 325mg/Oxycodone 10mg tab (Percocet)',
    'Acetaminophen 325 MG / Oxycodone Hydrochloride 5 MG Oral Tablet': 'APAP 325mg/Oxycodone 5mg tab',
    'Acetaminophen 325 MG / oxyCODONE Hydrochloride 5 MG Oral Tablet': 'APAP 325mg/Oxycodone 5mg tab',
    'Acetaminophen 325 MG Oral Tablet': 'APAP 325mg tab',
    'Acetaminophen 325 MG Oral Tablet [Tylenol]': 'APAP 325mg tab (Tylenol)',
    'Acetaminophen 500 MG Oral Tablet': 'APAP 500mg tab',
    'Alendronic acid 10 MG Oral Tablet': 'Alendronate 10mg tab',
    'Allopurinol 100 MG Oral Tablet': 'Allopurinol 100mg tab',
    'Alteplase 100 MG Injection': 'tPA 100mg inj',
    'Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet': 'Amox/Clav 250/125mg tab',
    'Amoxicillin 250 MG Oral Capsule': 'Amoxicillin 250mg cap',
    'Amoxicillin 500 MG Oral Tablet': 'Amoxicillin 500mg tab',
    'Aspirin 81 MG Oral Tablet': 'ASA 81mg tab',
    'Astemizole 10 MG Oral Tablet': 'Astemizole 10mg tab',
    'Aviptadil Infusion': 'Aviptadil inf',
    'Azithromycin 250 MG Oral Capsule': 'Azithromycin 250mg cap',
    'Breath-Actuated 120 ACTUAT beclomethasone dipropionate 0.04 MG/ACTUAT Metered Dose Inhaler [Qvar]': 'BA 120act Beclomethasone 0.04mg/act MDI (Qvar)',
    'Camila 28 Day Pack': 'Camila 28d pack',
    'Cefaclor 250 MG Oral Capsule': 'Cefaclor 250mg cap',
    'Cefuroxime 250 MG Oral Tablet': 'Cefuroxime 250mg tab',
    'Chlorpheniramine Maleate 2 MG/ML Oral Solution': 'CPM 2mg/ml soln',
    'Chlorpheniramine Maleate 4 MG Oral Tablet': 'CPM 4mg tab',
    'Cisplatin 50 MG Injection': 'Cisplatin 50mg inj',
    'Clindamycin 300mg': 'Clindamycin 300mg',
    'Clopidogrel 75 MG Oral Tablet': 'Clopidogrel 75mg tab',
    'Colchicine 0.6 MG Oral Tablet': 'Colchicine 0.6mg tab',
    'Diazepam 5 MG Oral Tablet': 'Diazepam 5mg tab',
    'Diazepam 5 MG/ML Injectable Solution': 'Diazepam 5mg/ml inj soln',
    'Digoxin 0.125 MG Oral Tablet': 'Digoxin 0.125mg tab',
    'Donepezil hydrochloride 10 MG Oral Tablet': 'Donepezil 10mg tab',
    'Donepezil hydrochloride 23 MG Oral Tablet': 'Donepezil 23mg tab',
    'Errin 28 Day Pack': 'Errin 28d pack',
    'Estrostep Fe 28 Day Pack': 'Estrostep Fe 28d pack',
    'Etonogestrel 68 MG Drug Implant': 'Etonogestrel 68mg implant',
    'FLUoxetine 20 MG Oral Capsule': 'Fluoxetine 20mg cap',
    'Fexofenadine hydrochloride 30 MG Oral Tablet': 'Fexofenadine 30mg tab',
    'Fexofenadine hydrochloride 60 MG Oral Tablet': 'Fexofenadine 60mg tab',
    'Furosemide 40 MG Oral Tablet': 'Lasix 40mg tab',
    'Galantamine 4 MG Oral Tablet': 'Galantamine 4mg tab',
    'Hydrochlorothiazide 25 MG Oral Tablet': 'HCTZ 25mg tab',
    'Hydrocortisone 10 MG/ML Topical Cream': 'Hydrocortisone 1% cream',
    'Ibuprofen 100 MG Oral Tablet': 'Ibuprofen 100mg tab',
    'Ibuprofen 200 MG Oral Tablet': 'Ibuprofen 200mg tab',
    'Ibuprofen 400 MG Oral Tablet [Ibu]': 'Ibuprofen 400mg tab (Ibu)',
    'Jolivette 28 Day Pack': 'Jolivette 28d pack',
    'Kyleena 19.5 MG Intrauterine System': 'Kyleena 19.5mg IUS',
    'Leucovorin 100 MG Injection': 'Leucovorin 100mg inj',
    'Levonorgestrel 0.00354 MG/HR Drug Implant': 'Levonorgestrel 0.00354mg/hr implant',
    'Levora 0.15/30 28 Day Pack': 'Levora 0.15/30 28d pack',
    'Levothyroxine Sodium 0.075 MG Oral Tablet': 'Levothyroxine 75mcg tab',
    'Liletta 52 MG Intrauterine System': 'Liletta 52mg IUS',
    'Loratadine 10 MG Oral Tablet': 'Loratadine 10mg tab',
    'Loratadine 5 MG Chewable Tablet': 'Loratadine 5mg chew tab',
    'Lorazepam 2 MG/ML Injectable Solution': 'Lorazepam 2mg/ml inj soln',
    'Memantine hydrochloride 2 MG/ML Oral Solution': 'Memantine 2mg/ml soln',
    'Meperidine Hydrochloride 50 MG Oral Tablet': 'Meperidine 50mg tab',
    'Mestranol / Norethynodrel': 'Mestranol/Norethynodrel',
    'Methotrexate 2.5 MG Oral Tablet': 'MTX 2.5mg tab',
    'Methylphenidate Hydrochloride 20 MG Oral Tablet': 'Methylphenidate 20mg tab',
    'Midazolam 1 MG/ML Injectable Solution': 'Midazolam 1mg/ml inj soln',
    'Milnacipran hydrochloride 100 MG Oral Tablet': 'Milnacipran 100mg tab',
    'Mirena 52 MG Intrauterine System': 'Mirena 52mg IUS',
    'NDA020503 200 ACTUAT Albuterol 0.09 MG/ACTUAT Metered Dose Inhaler': 'Albuterol 200act 0.09mg/act MDI',
    'NDA020503 200 ACTUAT albuterol 0.09 MG/ACTUAT Metered Dose Inhaler [Proventil]': 'Albuterol 200act 0.09mg/act MDI (Proventil)',
    'NDA020800 0.3 ML Epinephrine 1 MG/ML Auto-Injector': 'Epi-pen 0.3ml 1mg/ml',
    'NDA020983 200 ACTUAT albuterol 0.09 MG/ACTUAT Metered Dose Inhaler [Ventolin]': 'Albuterol 200act 0.09mg/act MDI (Ventolin)',
    'NDA021457 200 ACTUAT albuterol 0.09 MG/ACTUAT Metered Dose Inhaler [ProAir]': 'Albuterol 200act 0.09mg/act MDI (ProAir)',
    'Naproxen 500 MG Oral Tablet': 'Naproxen 500mg tab',
    'Naproxen sodium 220 MG Oral Tablet': 'Naproxen Na 220mg tab',
    'Natazia 28 Day Pack': 'Natazia 28d pack',
    'Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray': 'NTG 0.4mg/act spray',
    'Norinyl 1+50 28 Day Pack': 'Norinyl 1+50 28d pack',
    'NuvaRing 0.12/0.015 MG per 24HR 21 Day Vaginal System': 'NuvaRing 0.12/0.015mg 21d',
    'Ortho Tri-Cyclen 28 Day Pack': 'Ortho Tri-Cyclen 28d pack',
    'PACLitaxel 100 MG Injection': 'Paclitaxel 100mg inj',
    'Paclitaxel 100 MG Injection': 'Paclitaxel 100mg inj',
    'Penicillin G 375 MG/ML Injectable Solution': 'PCN G 375mg/ml inj soln',
    'Penicillin V Potassium 250 MG Oral Tablet': 'PCN VK 250mg tab',
    'Penicillin V Potassium 500 MG Oral Tablet': 'PCN VK 500mg tab',
    'Piperacillin 4000 MG / tazobactam 500 MG Injection': 'Pip/Tazo 4g/0.5g inj',
    'Rocuronium bromide 10 MG/ML Injectable Solution': 'Rocuronium 10mg/ml inj soln',
    'Seasonique 91 Day Pack': 'Seasonique 91d pack',
    'Simvastatin 10 MG Oral Tablet': 'Simvastatin 10mg tab',
    'Simvastatin 20 MG Oral Tablet': 'Simvastatin 20mg tab',
    'Sodium Chloride 9 MG/ML Injectable Solution': 'NS inj soln',
    'Tacrine 10 MG Oral Capsule': 'Tacrine 10mg cap',
    'Tamoxifen 10 MG Oral Tablet': 'Tamoxifen 10mg tab',
    'Terfenadine 60 MG Oral Tablet': 'Terfenadine 60mg tab',
    'Trinessa 28 Day Pack': 'Trinessa 28d pack',
    'Verzenio 100 MG Oral Tablet': 'Verzenio 100mg tab',
    'Vitamin B12 5 MG/ML Injectable Solution': 'Vit B12 5mg/ml inj soln',
    'Warfarin Sodium 5 MG Oral Tablet': 'Warfarin 5mg tab',
    'Yaz 28 Day Pack': 'Yaz 28d pack',
    'albuterol 0.21 MG/ML Inhalation Solution': 'Albuterol 0.21mg/ml neb soln',
    'albuterol 0.417 MG/ML Inhalation Solution': 'Albuterol 0.417mg/ml neb soln',
    'albuterol 0.83 MG/ML Inhalation Solution': 'Albuterol 0.83mg/ml neb soln',
    'albuterol 5 MG/ML Inhalation Solution': 'Albuterol 5mg/ml neb soln',
    'amLODIPine 2.5 MG Oral Tablet': 'Amlodipine 2.5mg tab',
    'amlodipine 2.5 MG / benazepril hydrochloride 10 MG Oral Capsule': 'Amlodipine 2.5mg/Benazepril 10mg cap',
    'amoxicillin 500 MG / clavulanate 125 MG Oral Tablet': 'Amox/Clav 500/125mg tab',
    'amoxicillin 875 MG / clavulanate 125 MG Oral Tablet': 'Amox/Clav 875/125mg tab',
    'anastrozole 1 MG Oral Tablet': 'Anastrozole 1mg tab',
    'aspirin 325 MG Oral Tablet': 'ASA 325mg tab',
    'aspirin 81 MG Oral Capsule': 'ASA 81mg cap',
    'aspirin 81 MG Oral Tablet': 'ASA 81mg tab',
    'atenolol 25 MG Oral Tablet': 'Atenolol 25mg tab',
    'atenolol 50 MG Oral Tablet': 'Atenolol 50mg tab',
    'atomoxetine 100 MG Oral Capsule': 'Atomoxetine 100mg cap',
    'atorvastatin 10 MG Oral Tablet': 'Atorvastatin 10mg tab',
    'atorvastatin 20 MG Oral Tablet': 'Atorvastatin 20mg tab',
    'atorvastatin 40 MG Oral Tablet': 'Atorvastatin 40mg tab',
    'atorvastatin 80 MG Oral Tablet': 'Atorvastatin 80mg tab',
    'benazepril hydrochloride 20 MG Oral Tablet': 'Benazepril 20mg tab',
    'benazepril hydrochloride 5 MG Oral Tablet': 'Benazepril 5mg tab',
    'bivalirudin 50 ML; 5 MG/ML Injection': 'Bivalirudin 50ml 5mg/ml inj',
    'budesonide 0.125 MG/ML Inhalation Suspension': 'Budesonide 0.125mg/ml neb susp',
    'budesonide 0.125 MG/ML Inhalation Suspension [Pulmicort]': 'Budesonide 0.125mg/ml neb susp (Pulmicort)',
    'budesonide 0.25 MG/ML Inhalation Suspension': 'Budesonide 0.25mg/ml neb susp',
    'buprenorphine 2 MG / naloxone 0.5 MG Sublingual Tablet': 'Buprenorphine 2mg/Naloxone 0.5mg SL tab',
    'carbamazepine 20 MG/ML Oral Suspension [Tegretol]': 'Carbamazepine 20mg/ml susp (Tegretol)',
    'carvedilol 12.5 MG Oral Tablet': 'Carvedilol 12.5mg tab',
    'carvedilol 25 MG Oral Tablet': 'Carvedilol 25mg tab',
    'carvedilol 3.125 MG Oral Tablet': 'Carvedilol 3.125mg tab',
    'carvedilol 6.25 MG Oral Tablet': 'Carvedilol 6.25mg tab',
    'cefazolin 2000 MG Injection': 'Cefazolin 2g inj',
    'cefpodoxime 200 MG Oral Tablet': 'Cefpodoxime 200mg tab',
    'ceftriaxone 1000 MG Injection': 'Ceftriaxone 1g inj',
    'cephalexin 500 MG Oral Tablet': 'Keflex 500mg tab',
    'cetirizine hydrochloride 10 MG Oral Tablet': 'Cetirizine 10mg tab',
    'cetirizine hydrochloride 5 MG Oral Tablet': 'Cetirizine 5mg tab',
    'ciprofloxacin 250 MG Oral Tablet': 'Cipro 250mg tab',
    'ciprofloxacin 500 MG Oral Tablet': 'Cipro 500mg tab',
    'clonazePAM 0.25 MG Oral Tablet': 'Clonazepam 0.25mg tab',
    'clopidogrel 300 MG Oral Tablet': 'Clopidogrel 300mg tab',
    'cycloSPORINE  modified 100 MG Oral Capsule': 'Cyclosporine mod 100mg cap',
    'darunavir 800 MG Oral Tablet': 'Darunavir 800mg tab',
    'desflurane 1000 MG/ML Inhalation Solution': 'Desflurane 1g/ml inh soln',
    'didanosine 400 MG Delayed Release Oral Capsule': 'Didanosine 400mg DR cap',
    'diphenhydrAMINE Hydrochloride 25 MG Oral Tablet': 'Benadryl 25mg tab',
    'doxycycline hyclate 100 MG': 'Doxycycline 100mg',
    'duloxetine 20 MG Delayed Release Oral Capsule': 'Duloxetine 20mg DR cap',
    'emtricitabine 200 MG / tenofovir disoproxil fumarate 300 MG Oral Tablet': 'FTC 200mg/TDF 300mg tab',
    'emtricitabine 200 MG Oral Capsule': 'FTC 200mg cap',
    'enalapril maleate 10 MG Oral Tablet': 'Enalapril 10mg tab',
    'enoxaparin sodium 100 MG/ML Injectable Solution': 'Enoxaparin 100mg/ml inj soln',
    'exemestane 25 MG Oral Tablet': 'Exemestane 25mg tab',
    'ferrous sulfate 325 MG Oral Tablet': 'Ferrous sulfate 325mg tab',
    'fosamprenavir 700 MG Oral Tablet': 'Fosamprenavir 700mg tab',
    'fosfomycin 3000 MG Powder': 'Fosfomycin 3g powder',
    'heparin sodium  porcine 100 UNT/ML Injectable Solution': 'Heparin 100u/ml inj soln',
    'heparin sodium  porcine 1000 UNT/ML Injectable Solution': 'Heparin 1000u/ml inj soln',
    'hydrochlorothiazide 12.5 MG / lisinopril 10 MG Oral Tablet': 'HCTZ 12.5mg/Lisinopril 10mg tab',
    'hydrochlorothiazide 12.5 MG / lisinopril 20 MG Oral Tablet': 'HCTZ 12.5mg/Lisinopril 20mg tab',
    'hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet': 'HCTZ 12.5mg/Valsartan 160mg tab',
    'hydrochlorothiazide 25 MG / losartan potassium 100 MG Oral Tablet': 'HCTZ 25mg/Losartan 100mg tab',
    'hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet': 'HCTZ 25mg/Valsartan 320mg tab',
    'indinavir 400 MG Oral Capsule': 'Indinavir 400mg cap',
    'insulin  regular  human 100 UNT/ML Injectable Solution': 'Regular insulin 100u/ml inj soln',
    'insulin isophane  human 70 UNT/ML / insulin  regular  human 30 UNT/ML Injectable Suspension [Humulin]': '70/30 insulin 100u/ml susp (Humulin)',
    'isoflurane 99.9 % Inhalation Solution': 'Isoflurane 99.9% inh soln',
    'labetalol hydrochloride 100 MG Oral Tablet': 'Labetalol 100mg tab',
    'lisinopril 10 MG Oral Tablet': 'Lisinopril 10mg tab',
    'lisinopril 2.5 MG Oral Tablet': 'Lisinopril 2.5mg tab',
    'lisinopril 20 MG Oral Tablet': 'Lisinopril 20mg tab',
    'lisinopril 30 MG Oral Tablet': 'Lisinopril 30mg tab',
    'lisinopril 40 MG Oral Tablet': 'Lisinopril 40mg tab',
    'lisinopril 5 MG Oral Tablet': 'Lisinopril 5mg tab',
    'losartan potassium 100 MG Oral Tablet': 'Losartan 100mg tab',
    'losartan potassium 25 MG Oral Tablet': 'Losartan 25mg tab',
    'losartan potassium 50 MG Oral Tablet': 'Losartan 50mg tab',
    'lovastatin 10 MG Oral Tablet': 'Lovastatin 10mg tab',
    'methadone hydrochloride 10 MG Oral Tablet': 'Methadone 10mg tab',
    'metoprolol tartrate 25 MG Oral Tablet': 'Metoprolol 25mg tab',
    'metoprolol tartrate 50 MG Oral Tablet': 'Metoprolol 50mg tab',
    'nebivolol 10 MG Oral Tablet [Bystolic]': 'Nebivolol 10mg tab (Bystolic)',
    'nebivolol 20 MG Oral Tablet [Bystolic]': 'Nebivolol 20mg tab (Bystolic)',
    'nebivolol 5 MG Oral Tablet [Bystolic]': 'Nebivolol 5mg tab (Bystolic)',
    'nicotine 7 MG/Day 24HR Transdermal System': 'Nicotine 7mg/d patch',
    'nitrofurantoin  macrocrystals 25 MG / nitrofurantoin  monohydrate 75 MG Oral Capsule': 'Macrobid 100mg cap',
    'nitroglycerin 0.4 MG Sublingual Tablet': 'NTG 0.4mg SL tab',
    'piperacillin 2000 MG / tazobactam 250 MG Injection': 'Pip/Tazo 2g/0.25g inj',
    'piperacillin 4000 MG / tazobactam 500 MG Injection': 'Pip/Tazo 4g/0.5g inj',
    'pitavastatin calcium 4 MG Oral Tablet [Livalo]': 'Pitavastatin 4mg tab (Livalo)',
    'prasugrel 10 MG Oral Tablet': 'Prasugrel 10mg tab',
    'pravastatin sodium 20 MG Oral Tablet': 'Pravastatin 20mg tab',
    'pravastatin sodium 40 MG Oral Tablet': 'Pravastatin 40mg tab',
    'pravastatin sodium 80 MG Oral Tablet': 'Pravastatin 80mg tab',
    'predniSONE 5 MG Oral Tablet': 'Prednisone 5mg tab',
    'pregabalin 100 MG Oral Capsule': 'Pregabalin 100mg cap',
    'propranolol hydrochloride 20 MG Oral Tablet': 'Propranolol 20mg tab',
    'propranolol hydrochloride 40 MG Oral Tablet': 'Propranolol 40mg tab',
    'quinapril 20 MG Oral Tablet': 'Quinapril 20mg tab',
    'quinapril 40 MG Oral Tablet': 'Quinapril 40mg tab',
    'remifentanil 2 MG Injection': 'Remifentanil 2mg inj',
    'ribociclib 200 MG Oral Tablet': 'Ribociclib 200mg tab',
    'ritonavir 100 MG Oral Capsule': 'Ritonavir 100mg cap',
    'rosuvastatin calcium 10 MG Oral Tablet': 'Rosuvastatin 10mg tab',
    'rosuvastatin calcium 40 MG Oral Tablet': 'Rosuvastatin 40mg tab',
    'rosuvastatin calcium 5 MG Oral Tablet': 'Rosuvastatin 5mg tab',
    'sacubitril 97 MG / valsartan 103 MG Oral Tablet': 'Sacubitril 97mg/Valsartan 103mg tab',
    'sevoflurane 1000 MG/ML Inhalation Solution': 'Sevoflurane 1g/ml inh soln',
    'simvastatin 10 MG Oral Tablet': 'Simvastatin 10mg tab',
    'simvastatin 20 MG Oral Tablet': 'Simvastatin 20mg tab',
    'simvastatin 40 MG Oral Tablet': 'Simvastatin 40mg tab',
    'sodium fluoride 0.0272 MG/MG Oral Gel': 'NaF 2.72% oral gel',
    'sulfamethoxazole 800 MG / trimethoprim 160 MG Oral Tablet': 'Bactrim DS tab',
    'tenecteplase 50 MG Injection': 'TNKase 50mg inj',
    'tenofovir disoproxil fumarate 300 MG Oral Tablet': 'TDF 300mg tab',
    'ticagrelor 90 MG Oral Tablet': 'Ticagrelor 90mg tab',
    'tramadol hydrochloride 50 MG Oral Tablet': 'Tramadol 50mg tab',
    'valsartan 320 MG Oral Tablet': 'Valsartan 320mg tab',
    'valsartan 40 MG Oral Tablet': 'Valsartan 40mg tab',
    'vancomycin 1000 MG Injection': 'Vancomycin 1g inj',
    'verapamil hydrochloride 80 MG Oral Tablet': 'Verapamil 80mg tab',
    'warfarin sodium 5 MG Oral Tablet': 'Warfarin 5mg tab',
    'zalcitabine 0.75 MG Oral Tablet': 'Zalcitabine 0.75mg tab',
    'zidovudine 300 MG Oral Tablet': 'AZT 300mg tab'
}

conditions_short_map = {
    'Abnormal findings diagnostic imaging heart+coronary circulat (finding)': 'Abn cardiac img',
    'Acute ST segment elevation myocardial infarction (disorder)': 'STEMI',
    'Acute allergic reaction (disorder)': 'Acute allergy',
    'Acute bacterial sinusitis (disorder)': 'Acute bact sinusitis',
    'Acute bronchitis (disorder)': 'Acute bronchitis',
    'Acute cholecystitis (disorder)': 'Acute cholecystitis',
    'Acute deep venous thrombosis (disorder)': 'Acute DVT',
    'Acute infective cystitis (disorder)': 'Acute cystitis',
    'Acute myeloid leukemia (disorder)': 'AML',
    'Acute non-ST segment elevation myocardial infarction (disorder)': 'NSTEMI',
    'Acute pulmonary embolism (disorder)': 'Acute PE',
    'Acute respiratory distress syndrome (disorder)': 'ARDS',
    'Acute respiratory failure (disorder)': 'ARF',
    'Acute viral pharyngitis (disorder)': 'Acute viral pharyngitis',
    'Alcoholism (disorder)': 'Alcoholism',
    'Alveolitis of jaw (disorder)': 'Jaw alveolitis',
    "Alzheimer's disease (disorder)": "Alzheimer's",
    'Anemia (disorder)': 'Anemia',
    'Aortic valve regurgitation (disorder)': 'Aortic regurg',
    'Aortic valve stenosis (disorder)': 'Aortic stenosis',
    'Appendicitis (disorder)': 'Appendicitis',
    'Asthma (disorder)': 'Asthma',
    'Atopic dermatitis (disorder)': 'Atopic derm',
    'Atrial fibrillation (disorder)': 'AFib',
    'Awaiting transplantation of bone marrow (situation)': 'Awaiting BMT',
    'Awaiting transplantation of kidney (situation)': 'Awaiting kidney tx',
    'Bacteremia (finding)': 'Bacteremia',
    'Bacterial infectious disease (disorder)': 'Bacterial infxn',
    'Bleeding from anus (disorder)': 'Rectal bleeding',
    'Blighted ovum (disorder)': 'Blighted ovum',
    'Body mass index 30+ - obesity (finding)': 'Obesity BMI>30',
    'Body mass index 40+ - severely obese (finding)': 'Severe obesity BMI>40',
    'Bullet wound (disorder)': 'GSW',
    'Burn injury (morphologic abnormality)': 'Burn',
    'Carcinoma in situ of prostate (disorder)': 'Prostate CIS',
    'Cerebral palsy (disorder)': 'CP',
    'Cerebrovascular accident (disorder)': 'CVA',
    'Child attention deficit disorder (disorder)': 'ADHD',
    'Childhood asthma (disorder)': 'Childhood asthma',
    'Chill (finding)': 'Chills',
    'Chronic congestive heart failure (disorder)': 'Chronic CHF',
    'Chronic intractable migraine without aura (disorder)': 'Chronic migraine',
    'Chronic kidney disease stage 1 (disorder)': 'CKD stage 1',
    'Chronic kidney disease stage 2 (disorder)': 'CKD stage 2',
    'Chronic kidney disease stage 3 (disorder)': 'CKD stage 3',
    'Chronic kidney disease stage 4 (disorder)': 'CKD stage 4',
    'Chronic low back pain (finding)': 'Chronic LBP',
    'Chronic neck pain (finding)': 'Chronic neck pain',
    'Chronic obstructive bronchitis (disorder)': 'COPD',
    'Chronic pain (finding)': 'Chronic pain',
    'Chronic sinusitis (disorder)': 'Chronic sinusitis',
    'Closed fracture of hip (disorder)': 'Closed hip fx',
    'Complete miscarriage (disorder)': 'Complete miscarriage',
    'Complication occurring during pregnancy (disorder)': 'Pregnancy comp',
    'Concussion injury of brain (disorder)': 'Concussion',
    'Concussion with loss of consciousness (disorder)': 'Concussion w/ LOC',
    'Concussion with no loss of consciousness (disorder)': 'Concussion w/o LOC',
    'Congenital uterine anomaly (disorder)': 'Congenital uterine anomaly',
    'Contact dermatitis (disorder)': 'Contact derm',
    'Cough (finding)': 'Cough',
    'Dental filling lost (finding)': 'Lost filling',
    'Dependent drug abuse (disorder)': 'Drug dependency',
    'Diabetes mellitus type 2 (disorder)': 'DM2',
    'Diarrhea symptom (finding)': 'Diarrhea',
    'Died in hospice (finding)': 'Hospice death',
    'Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)': 'COVID-19',
    'Dislocation of hip joint (disorder)': 'Hip dislocation',
    'Disorder of kidney due to diabetes mellitus (disorder)': 'Diabetic nephropathy',
    'Drug overdose': 'Drug OD',
    'Dyspnea (finding)': 'SOB',
    'Eclampsia in pregnancy (disorder)': 'Eclampsia',
    'Educated to high school level (finding)': 'HS education',
    'End-stage renal disease (disorder)': 'ESRD',
    'Epidermal burn of skin (disorder)': 'Skin burn',
    'Epilepsy (disorder)': 'Epilepsy',
    'Essential hypertension (disorder)': 'HTN',
    'Excessive salivation (disorder)': 'Hypersalivation',
    'Facial laceration (disorder)': 'Facial lac',
    "Familial Alzheimer's disease of early onset (disorder)": "Early onset Alzheimer's",
    'Fatigue (finding)': 'Fatigue',
    'Febrile neutropenia (disorder)': 'Febrile neutropenia',
    'Fetus with chromosomal abnormality (disorder)': 'Fetal chromosomal abn',
    'Fever (finding)': 'Fever',
    'Fibromyalgia (disorder)': 'Fibromyalgia',
    'Fracture of ankle (disorder)': 'Ankle fx',
    'Fracture of bone (disorder)': 'Bone fx',
    'Fracture of clavicle (disorder)': 'Clavicle fx',
    'Fracture of forearm (disorder)': 'Forearm fx',
    'Fracture of mandible (disorder)': 'Mandible fx',
    'Fracture of rib (disorder)': 'Rib fx',
    'Fracture of vertebral column with spinal cord injury (disorder)': 'Vertebral fx w/ SCI',
    'Fracture subluxation of wrist (disorder)': 'Wrist sublux fx',
    'Fractured dental filling (finding)': 'Fractured filling',
    'Full thickness burn (disorder)': 'Full thickness burn',
    'Full-time employment (finding)': 'Full-time employed',
    'Gallbladder calculus (disorder)': 'Gallstones',
    'Gastroesophageal reflux disease (disorder)': 'GERD',
    'Gingival disease (disorder)': 'Gum disease',
    'Gingivitis (disorder)': 'Gingivitis',
    'Gunshot wound (disorder)': 'GSW',
    'Has a criminal record (finding)': 'Criminal record',
    'Headache (finding)': 'HA',
    'Heart failure (disorder)': 'HF',
    'Hemoptysis (finding)': 'Hemoptysis',
    'High risk pregnancy (finding)': 'High risk preg',
    'History of allotransplantation of bone marrow (situation)': 'H/o BMT',
    'History of amputation of foot (situation)': 'H/o foot amp',
    'History of aortic valve replacement (situation)': 'H/o AVR',
    'History of appendectomy (situation)': 'H/o appendectomy',
    'History of artificial joint (situation)': 'H/o artif joint',
    'History of autologous bone marrow transplant (situation)': 'H/o auto BMT',
    'History of coronary artery bypass grafting (situation)': 'H/o CABG',
    'History of myocardial infarction (situation)': 'H/o MI',
    'History of peripheral stem cell transplant (situation)': 'H/o PSCT',
    'History of renal transplant (situation)': 'H/o renal tx',
    'History of seizure (situation)': 'H/o seizure',
    'History of tubal ligation (situation)': 'H/o tubal',
    'Homeless (finding)': 'Homeless',
    'Housing unsatisfactory (finding)': 'Poor housing',
    'Human immunodeficiency virus infection (disorder)': 'HIV',
    'Hyperglycemia (disorder)': 'Hyperglycemia',
    'Hyperlipidemia (disorder)': 'HLD',
    'Hypertriglyceridemia (disorder)': 'HTG',
    'Hypoxemia (disorder)': 'Hypoxemia',
    'Idiopathic atrophic hypothyroidism (disorder)': 'Hypothyroidism',
    'Impacted molars (disorder)': 'Impacted molars',
    'Infection of tooth (disorder)': 'Tooth infxn',
    'Inflammatory disorder due to increased blood urate level (disorder)': 'Gout',
    'Injury of anterior cruciate ligament (disorder)': 'ACL injury',
    'Injury of heart (disorder)': 'Heart injury',
    'Injury of knee (disorder)': 'Knee injury',
    'Injury of medial collateral ligament of knee (disorder)': 'MCL injury',
    'Injury of neck (disorder)': 'Neck injury',
    'Injury of tendon of the rotator cuff of shoulder (disorder)': 'Rotator cuff injury',
    'Intellectual disability (disorder)': 'ID',
    'Ischemic heart disease (disorder)': 'IHD',
    'Joint pain (finding)': 'Joint pain',
    'Kidney transplant failure and rejection (disorder)': 'Kidney tx rejection',
    'Laceration - injury (disorder)': 'Lac',
    'Laceration of foot (disorder)': 'Foot lac',
    'Laceration of forearm (disorder)': 'Forearm lac',
    'Laceration of hand (disorder)': 'Hand lac',
    'Laceration of thigh (disorder)': 'Thigh lac',
    'Lack of access to transportation (finding)': 'No transport',
    'Leaking dental filling (finding)': 'Leaking filling',
    'Leukemia  disease (disorder)': 'Leukemia',
    'Limited social contact (finding)': 'Limited social contact',
    'Localized  primary osteoarthritis of the hand (disorder)': 'Hand OA',
    'Loose dental filling (finding)': 'Loose filling',
    'Loss of taste (finding)': 'Ageusia',
    'Loss of teeth (disorder)': 'Tooth loss',
    'Macular edema and retinopathy due to type 2 diabetes mellitus (disorder)': 'Diabetic macular edema',
    'Major depressive disorder (disorder)': 'MDD',
    'Malignant neoplasm of breast (disorder)': 'Breast CA',
    'Malignant neoplasm of colon (disorder)': 'Colon CA',
    'Medication review due (situation)': 'Med review due',
    'Metabolic syndrome X (disorder)': 'MetS',
    'Metastatic malignant neoplasm to colon (disorder)': 'Mets to colon',
    'Metastatic malignant neoplasm to prostate (disorder)': 'Mets to prostate',
    'Microalbuminuria due to type 2 diabetes mellitus (disorder)': 'Diabetic microalbumin',
    'Miscarriage in first trimester (disorder)': '1st tri miscarriage',
    'Miscarriage in second trimester (disorder)': '2nd tri miscarriage',
    'Misuses drugs (finding)': 'Drug misuse',
    'Mitral valve regurgitation (disorder)': 'MR',
    'Multiple myeloma (disorder)': 'MM',
    'Muscle pain (finding)': 'Myalgia',
    'Myocardial infarction (disorder)': 'MI',
    'Nasal congestion (finding)': 'Nasal congestion',
    'Nausea (finding)': 'N',
    'Neoplasm of prostate (disorder)': 'Prostate neoplasm',
    'Neuropathy due to type 2 diabetes mellitus (disorder)': 'Diabetic neuropathy',
    'Non-small cell carcinoma of lung  TNM stage 1 (disorder)': 'NSCLC stage 1',
    'Non-small cell lung cancer (disorder)': 'NSCLC',
    'Nonproliferative retinopathy due to type 2 diabetes mellitus (disorder)': 'NPDR',
    'Normal pregnancy (finding)': 'Normal preg',
    'Not in labor force (finding)': 'Not in workforce',
    'Obstructive sleep apnea syndrome (disorder)': 'OSA',
    'Only received primary school education (finding)': 'Primary ed only',
    'Opioid abuse (disorder)': 'Opioid abuse',
    'Osteoarthritis of hip (disorder)': 'Hip OA',
    'Osteoarthritis of knee (disorder)': 'Knee OA',
    'Osteoporosis (disorder)': 'Osteoporosis',
    'Osteoporotic fracture of bone (disorder)': 'Osteoporotic fx',
    'Otitis media (disorder)': 'OM',
    'Overlapping malignant neoplasm of colon (disorder)': 'Overlapping colon CA',
    'Pain (finding)': 'Pain',
    'Part-time employment (finding)': 'Part-time employed',
    'Partial thickness burn (disorder)': 'Partial thickness burn',
    'Past pregnancy history of miscarriage (situation)': 'H/o miscarriage',
    'Perennial allergic rhinitis (disorder)': 'Perennial allergic rhinitis',
    'Perennial allergic rhinitis with seasonal variation (disorder)': 'Perennial/seasonal rhinitis',
    'Pneumonia (disorder)': 'PNA',
    'Polyp of colon (disorder)': 'Colon polyp',
    'Poor muscle tone (finding)': 'Poor muscle tone',
    'Posttraumatic stress disorder (disorder)': 'PTSD',
    'Pre-eclampsia (disorder)': 'Pre-eclampsia',
    'Prediabetes (finding)': 'Prediabetes',
    'Preinfarction syndrome (disorder)': 'Preinfarction',
    'Primary dental caries (disorder)': 'Dental caries',
    'Primary fibromyalgia syndrome (disorder)': '1° fibromyalgia',
    'Primary malignant neoplasm of colon (disorder)': '1° colon CA',
    'Proliferative retinopathy due to type 2 diabetes mellitus (disorder)': 'PDR',
    'Proteinuria due to type 2 diabetes mellitus (disorder)': 'Diabetic proteinuria',
    'Protracted diarrhea (finding)': 'Protracted diarrhea',
    'Pulmonary emphysema (disorder)': 'Emphysema',
    'Pulmonic valve stenosis (disorder)': 'PS',
    'Pyelonephritis (disorder)': 'Pyelo',
    'Received higher education (finding)': 'Higher ed',
    'Recurrent rectal polyp (disorder)': 'Recurrent rectal polyp',
    'Recurrent urinary tract infection (disorder)': 'Recurrent UTI',
    'Refugee (person)': 'Refugee',
    'Reports of violence in the environment (finding)': 'Enviro violence',
    'Resorption of alveolar process due to dental trauma (disorder)': 'Alveolar resorption',
    'Respiratory distress (finding)': 'Resp distress',
    'Retinopathy due to type 2 diabetes mellitus (disorder)': 'Diabetic retinopathy',
    'Rheumatoid arthritis (disorder)': 'RA',
    'Risk activity involvement (finding)': 'Risk behaviors',
    'Rupture of appendix (disorder)': 'Ruptured appendix',
    'Rupture of patellar tendon (disorder)': 'Patellar tendon rupture',
    'Seasonal allergic rhinitis (disorder)': 'Seasonal allergies',
    'Seizure disorder (disorder)': 'Seizure d/o',
    'Sepsis (disorder)': 'Sepsis',
    'Sepsis caused by virus (disorder)': 'Viral sepsis',
    'Septic shock (disorder)': 'Septic shock',
    'Serving in military service (finding)': 'Military service',
    'Severe anxiety (panic) (finding)': 'Severe anxiety',
    'Shock (disorder)': 'Shock',
    'Sinusitis (disorder)': 'Sinusitis',
    'Sleep apnea (disorder)': 'Sleep apnea',
    'Sleep disorder (disorder)': 'Sleep d/o',
    'Smokes tobacco daily (finding)': 'Daily smoker',
    'Social isolation (finding)': 'Social isolation',
    'Social migrant (finding)': 'Social migrant',
    'Sore throat (finding)': 'Sore throat',
    'Spasticity (finding)': 'Spasticity',
    'Sprain (morphologic abnormality)': 'Sprain',
    'Sprain of ankle (disorder)': 'Ankle sprain',
    'Sprain of wrist (disorder)': 'Wrist sprain',
    'Sputum finding (finding)': 'Sputum',
    'Sterilization requested (situation)': 'Sterilization req',
    'Streptococcal sore throat (disorder)': 'Strep throat',
    'Stress (finding)': 'Stress',
    'Suspected disease caused by Severe acute respiratory coronavirus 2 (situation)': 'R/O COVID',
    'Suspected lung cancer (situation)': 'R/O lung CA',
    'Suspected prostate cancer (situation)': 'R/O prostate CA',
    'Tear of meniscus of knee (disorder)': 'Meniscus tear',
    'Tongue tie (disorder)': 'Ankyloglossia',
    'Torus mandibularis (disorder)': 'Torus mandibularis',
    'Torus palatinus (disorder)': 'Torus palatinus',
    'Transformed migraine (disorder)': 'Transformed migraine',
    'Transport problem (finding)': 'Transport issues',
    'Traumatic brain injury (disorder)': 'TBI',
    'Traumatic dislocation of temporomandibular joint (disorder)': 'TMJ dislocation',
    'Traumatic injury of spinal cord and/or vertebral column (disorder)': 'SCI',
    'Traumatic or nontraumatic brain injury (disorder)': 'Brain injury',
    'Tricuspid valve regurgitation (disorder)': 'TR',
    'Tricuspid valve stenosis (disorder)': 'TS',
    'Tubal pregnancy (disorder)': 'Ectopic preg',
    'Unable to swallow saliva (finding)': 'Cannot swallow saliva',
    'Unemployed (finding)': 'Unemployed',
    'Unhealthy alcohol drinking behavior (finding)': 'Unhealthy alcohol use',
    'Victim of intimate partner abuse (finding)': 'IPV',
    'Viral sinusitis (disorder)': 'Viral sinusitis',
    'Vomiting symptom (finding)': 'V',
    'Wheezing (finding)': 'Wheezing',
    'Whiplash injury to neck (disorder)': 'Whiplash'
}

procedures_short_map = {
    '12 lead electrocardiogram (procedure)': '12 lead ECG',
    'Absolute CD4 count procedure (procedure)': 'Abs CD4 count',
    'Administration of anesthesia AND/OR sedation (procedure)': 'Anesth/sedation admin',
    'Administration of anesthesia for procedure (procedure)': 'Proc anesth admin',
    'Administration of vaccine product containing only Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae antigens (procedure)': 'DTaP vax admin',
    'Admission to burn unit (procedure)': 'Burn unit admit',
    'Admission to intensive care unit (procedure)': 'ICU admit',
    'Admission to long stay hospital (procedure)': 'Long stay hosp admit',
    'Admission to orthopedic department (procedure)': 'Ortho admit',
    'Admission to trauma surgery department (procedure)': 'Trauma surg admit',
    'Admission to ward (procedure)': 'Ward admit',
    'Allergy screening test (procedure)': 'Allergy screen',
    'Allogeneic bone marrow transplantation (procedure)': 'Allo BMT',
    'Alpha-fetoprotein test - antenatal (procedure)': 'Antenatal AFP',
    'Angiography of coronary artery (procedure)': 'Coronary angio',
    'Antenatal RhD antibody screening (procedure)': 'Antenatal RhD screen',
    'Antibiotic therapy (procedure)': 'Abx therapy',
    'Anticipatory guidance (procedure)': 'Anticipatory guide',
    'Application of composite dental filling material to dentin of tooth following fracture of tooth (procedure)': 'Dental composite post-fx',
    'Application of dressing  sterile (procedure)': 'Sterile dressing',
    'Artificial ventilation (regime/therapy)': 'Art vent',
    'Assessment of anxiety (procedure)': 'Anxiety assess',
    'Assessment of cardiac status using monitoring device (procedure)': 'Cardiac monitor assess',
    'Assessment of health and social care needs (procedure)': 'Health/social needs assess',
    'Assessment of readiness for disclosure of health status (procedure)': 'Health discl readiness',
    'Assessment of readiness for self-management (procedure)': 'Self-mgmt readiness',
    'Assessment of social support (procedure)': 'Social support assess',
    'Assessment of substance use (procedure)': 'Substance use assess',
    'Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)': 'AUDIT-C assess',
    'Assessment using Canadian Study of Health and Aging Clinical Frailty Scale (procedure)': 'CSHA frailty assess',
    'Assessment using Car  Relax  Alone  Forget  Friends  Trouble Screening Test (procedure)': 'CRAFFT screen',
    'Assessment using Morse Fall Scale (procedure)': 'Morse fall assess',
    'Assessment using New York Heart Association Classification (procedure)': 'NYHA class assess',
    'Assessment using health assessment questionnaire (procedure)': 'HAQ assess',
    'Assist control ventilation (regime/therapy)': 'AC vent',
    'Asthma screening (procedure)': 'Asthma screen',
    'Augmentation of labor (procedure)': 'Labor augment',
    'Auscultation of the fetal heart (procedure)': 'Fetal heart auscult',
    'Autologous bone marrow transplant (procedure)': 'Auto BMT',
    'Biopsy of breast (procedure)': 'Breast bx',
    'Biopsy of colon (procedure)': 'Colon bx',
    'Biopsy of prostate (procedure)': 'Prostate bx',
    'Blood group typing (procedure)': 'Blood typing',
    'Bone density scan (procedure)': 'DEXA scan',
    'Bone immobilization (procedure)': 'Bone immob',
    'Brachytherapy of breast (procedure)': 'Breast brachy',
    'Brief general examination (procedure)': 'Brief exam',
    'Cannulation (procedure)': 'Cannulation',
    'Cardiopulmonary bypass operation (procedure)': 'CPB',
    'Cardiovascular stress testing (procedure)': 'CV stress test',
    'Care planning and problem solving actions (procedure)': 'Care plan',
    'Care regimes assessment (procedure)': 'Care regime assess',
    'Catheter ablation of tissue of heart (procedure)': 'Cardiac cath ablation',
    'Certification procedure (procedure)': 'Certification',
    'Cesarean section (procedure)': 'C-section',
    'Chemotherapy (procedure)': 'Chemo',
    'Childbirth': 'Delivery',
    'Chlamydia antigen test (procedure)': 'Chlamydia Ag test',
    'Close observation (regime/therapy)': 'Close obs',
    'Closed reduction of dislocation of temporomandibular joint (procedure)': 'TMJ closed reduction',
    'Closed reduction of mandibular fracture (procedure)': 'Mandib fx closed reduction',
    'Cognitive and behavioral therapy (regime/therapy)': 'CBT',
    'Colonoscopy (procedure)': 'Colonoscopy',
    'Combined chemotherapy and radiation therapy (procedure)': 'Chemorad',
    'Complete blood count (procedure)': 'CBC',
    'Complete blood count with white cell differential  automated (procedure)': 'CBC w/diff',
    'Comprehensive interview and evaluation (procedure)': 'Comp eval',
    'Comprehensive metabolic panel (procedure)': 'CMP',
    'Computed tomography of chest  abdomen and pelvis (procedure)': 'CT CAP',
    'Computed tomography of chest and abdomen (procedure)': 'CT CA',
    'Computed tomography of head (procedure)': 'Head CT',
    'Consultation for treatment (procedure)': 'Tx consult',
    'Continuous positive airway pressure titration (procedure)': 'CPAP titration',
    'Continuous subcutaneous infusion of insulin (procedure)': 'CSII',
    'Coordination of care plan (procedure)': 'Care plan coord',
    'Coronary artery bypass grafting (procedure)': 'CABG',
    'Counseling for termination of pregnancy (procedure)': 'TOP counseling',
    'Cytopathology procedure  preparation of smear  genital source (procedure)': 'Genital cyto smear',
    'Death in hospital (event)': 'In-hosp death',
    'Dental application of desensitizing medicament (procedure)': 'Dental desensitizing',
    'Dental care (regime/therapy)': 'Dental care',
    'Dental consultation and report (procedure)': 'Dental consult',
    'Dental fluoride treatment (procedure)': 'Dental fluoride',
    'Dental plain X-ray bitewing (procedure)': 'Dental bitewing',
    'Dental surgical procedure (procedure)': 'Dental surgery',
    'Depression screening (procedure)': 'Depression screen',
    'Depression screening using Patient Health Questionnaire Nine Item score (procedure)': 'PHQ-9 screen',
    'Detection of chromosomal aneuploidy in prenatal amniotic fluid specimen using fluorescence in situ hybridization screening technique (procedure)': 'Amnio FISH aneuploidy',
    'Development of individualized plan of care (procedure)': 'Indiv care plan',
    'Diagnostic assessment (procedure)': 'Dx assess',
    'Digital examination of rectum (procedure)': 'DRE',
    'Direct current cardioversion (procedure)': 'DC cardioversion',
    'Discharge from hospital (procedure)': 'Hosp d/c',
    'Discharge to ward (procedure)': 'Ward d/c',
    'Discussion about options (procedure)': 'Options disc',
    'Discussion about pregnancy (procedure)': 'Preg disc',
    'Discussion about signs and symptoms (procedure)': 'S/S disc',
    'Discussion about treatment (procedure)': 'Tx disc',
    'Documentation procedure (procedure)': 'Documentation',
    'Doppler ultrasonography of artery (procedure)': 'Arterial doppler',
    'Echocardiography (procedure)': 'Echo',
    'Education  guidance and counseling (procedure)': 'Ed/counsel',
    'Electrocardiographic procedure (procedure)': 'ECG',
    'Electroencephalogram (procedure)': 'EEG',
    'Emergency coronary artery bypass graft (procedure)': 'Emerg CABG',
    'Epidural anesthesia (procedure)': 'Epidural',
    'Episiotomy (procedure)': 'Episiotomy',
    'Evaluating response to treatment (procedure)': 'Tx response eval',
    'Evaluation of uterine fundal height (procedure)': 'Fundal height eval',
    'Evaluation procedure (procedure)': 'Evaluation',
    'Examination of gingivae (procedure)': 'Gingival exam',
    'Excision of appendix (procedure)': 'Appendectomy',
    'Excision of axillary lymph node (procedure)': 'Axillary node excision',
    'Excision of breast tissue (procedure)': 'Breast tissue excision',
    'Excision of fallopian tube and surgical removal of ectopic pregnancy (procedure)': 'Ectopic preg removal',
    'Excision of lingual frenum (procedure)': 'Lingual frenectomy',
    'Excision of lingual torus (procedure)': 'Lingual torus excision',
    'Excision of maxillary torus palatinus (procedure)': 'Torus palatinus excision',
    'Excision of sentinel lymph node (procedure)': 'SLN excision',
    'Exercise class (regime/therapy)': 'Exercise class',
    'External beam radiation therapy procedure (procedure)': 'EBRT',
    'Extraction of wisdom tooth (procedure)': 'Wisdom tooth ext',
    'Face mask (physical object)': 'Face mask',
    'Fetal anatomy study (procedure)': 'Fetal anatomy scan',
    'Fiberoptic bronchoscopy (procedure)': 'FOB',
    'Fine needle aspiration biopsy of lung (procedure)': 'Lung FNA',
    'Fitting of denture (procedure)': 'Denture fitting',
    'Gingivectomy or gingivoplasty  per tooth (procedure)': 'Gingivectomy',
    'Gonorrhea infection titer test (procedure)': 'GC titer',
    'Grafting of periodontal bone defect (procedure)': 'Perio bone graft',
    'Health risks education (procedure)': 'Health risk ed',
    'Hearing examination (procedure)': 'Hearing exam',
    'Heart failure education (procedure)': 'HF ed',
    'Hematologic disorder medication review (procedure)': 'Hemato med review',
    'Hemodialysis (procedure)': 'HD',
    'Hemogram  automated  with red blood cells  white blood cells  hemoglobin  hematocrit  indices  platelet count  and manual white blood cell differential (procedure)': 'Complete hemogram w/diff',
    'Hemopoietic stem cell transplant (procedure)': 'HSCT',
    'Heparin therapy (procedure)': 'Heparin tx',
    'Hepatitis B screening (procedure)': 'Hep B screen',
    'Hepatitis B surface antigen measurement (procedure)': 'HBsAg',
    'Hepatitis C antibody  confirmatory test (procedure)': 'Hep C Ab confirm',
    'Hepatitis C screening (procedure)': 'Hep C screen',
    'Hepatitis antibody test (procedure)': 'Hep Ab test',
    'High resolution computed tomography of chest without contrast (procedure)': 'HRCT chest w/o contrast',
    'History AND physical examination (procedure)': 'H&P',
    'History and physical examination  limited (procedure)': 'Limited H&P',
    'History and physical examination with evaluation and management of patient (procedure)': 'H&P w/E&M',
    'History taking (procedure)': 'History',
    'Home health aide service (regime/therapy)': 'HHA service',
    'Hospice care (regime/therapy)': 'Hospice',
    'Human epidermal growth factor receptor 2 gene detection by fluorescence in situ hybridization (procedure)': 'HER2 FISH',
    'Human epidermal growth factor receptor 2 gene detection by immunohistochemistry (procedure)': 'HER2 IHC',
    'Human immunodeficiency virus antigen test (procedure)': 'HIV Ag test',
    'Human immunodeficiency virus counseling (procedure)': 'HIV counsel',
    'Human immunodeficiency virus screening (procedure)': 'HIV screen',
    'Human immunodeficiency virus viral load (procedure)': 'HIV VL',
    'Imaging finding (finding)': 'Imaging finding',
    'Incision (procedure)': 'Incision',
    'Induced cardioplegia (procedure)': 'Cardioplegia',
    'Induced termination of pregnancy (procedure)': 'TOP',
    'Information gathering (procedure)': 'Info gathering',
    'Initial patient assessment (procedure)': 'Initial assess',
    'Injection of epinephrine (procedure)': 'Epi inj',
    'Injection of tetanus antitoxin (procedure)': 'Tetanus antitoxin',
    'Insertion of catheter into artery (procedure)': 'Arterial line',
    'Insertion of endotracheal tube (procedure)': 'ETT insertion',
    'Insertion of intrauterine contraceptive device (procedure)': 'IUD insertion',
    'Insertion of subcutaneous contraceptive (procedure)': 'SC contraceptive insert',
    'Instrumental delivery (procedure)': 'Instrumental delivery',
    'Interstitial brachytherapy (procedure)': 'Interstitial brachy',
    'Intramuscular injection (procedure)': 'IM inj',
    'Intraoperative care (regime/therapy)': 'Intraop care',
    'Intravenous blood transfusion of packed cells (procedure)': 'IV PRBC',
    'Intubation (procedure)': 'Intubation',
    'Kitchen practice (regime/therapy)': 'Kitchen practice',
    'Lab findings education  guidance  and counseling (procedure)': 'Lab results counsel',
    'Laboratory test (procedure)': 'Lab test',
    'Laparoscopic cholecystectomy (procedure)': 'Lap chole',
    'Liaising with referral source (procedure)': 'Referral liaison',
    'Ligation of bilateral fallopian tubes (procedure)': 'BTL',
    'Lumpectomy of breast (procedure)': 'Breast lumpectomy',
    'Lung volume reduction surgery (procedure)': 'LVRS',
    'Magnetic resonance imaging for measurement of brain volume (procedure)': 'Brain vol MRI',
    'Magnetic resonance imaging of breast (procedure)': 'Breast MRI',
    'Mammogram - symptomatic (procedure)': 'Symptomatic mammo',
    'Mammography (procedure)': 'Mammogram',
    'Manual pelvic examination (procedure)': 'Pelvic exam',
    'Measurement of Varicella-zoster virus antibody (procedure)': 'VZV Ab',
    'Measurement of respiratory function (procedure)': 'PFT',
    'Median sternotomy (procedure)': 'Median sternotomy',
    'Medical induction of labor (procedure)': 'Med induction',
    'Medical records review (procedure)': 'Chart review',
    'Medication reconciliation (procedure)': 'Med rec',
    'Mental health screening (procedure)': 'MH screen',
    'Methotrexate injection into tubal pregnancy (procedure)': 'MTX for ectopic',
    'Microbial culture (procedure)': 'Culture',
    'Monitoring of patient (regime/therapy)': 'Patient monitoring',
    'Movement therapy (regime/therapy)': 'Movement therapy',
    'Multidisciplinary assessment (procedure)': 'MDT assess',
    'Nasal sinus endoscopy (procedure)': 'Sinus endo',
    'Notification of treatment plan (procedure)': 'Tx plan notif',
    'Notifications (procedure)': 'Notifications',
    'Nursing care/supplementary surveillance (regime/therapy)': 'Nursing care',
    'Occupational therapy (regime/therapy)': 'OT',
    'Off-pump coronary artery bypass (procedure)': 'OPCAB',
    'Operative procedure planned (situation)': 'OR planned',
    'Oral examination (procedure)': 'Oral exam',
    'Oral health education (procedure)': 'Oral health ed',
    'Oxygen administration by mask (procedure)': 'O2 mask',
    'Partial resection of colon (procedure)': 'Partial colectomy',
    'Passive immunization (procedure)': 'Passive immun',
    'Patient discharge (procedure)': 'Pt d/c',
    'Patient informed - test result (situation)': 'Pt informed of results',
    'Patient referral (procedure)': 'Pt referral',
    'Patient referral for dental care (procedure)': 'Dental referral',
    'Patient transfer  in-hospital (procedure)': 'In-hosp transfer',
    'Percutaneous coronary intervention (procedure)': 'PCI',
    'Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance with contrast (procedure)': 'Portal vein thrombectomy',
    'Peripheral blood smear interpretation (procedure)': 'Periph smear interp',
    'Physical examination  complete (procedure)': 'Complete PE',
    'Physical examination procedure (procedure)': 'PE',
    'Physical therapy procedure (regime/therapy)': 'PT',
    'Placement of aortic cross clamp (procedure)': 'Aortic cross clamp',
    'Placing subject in prone position (procedure)': 'Prone position',
    'Plain X-ray of ankle region (procedure)': 'Ankle XR',
    'Plain X-ray of chest (procedure)': 'CXR',
    'Plain X-ray of clavicle (procedure)': 'Clavicle XR',
    'Plain X-ray of humerus (procedure)': 'Humerus XR',
    'Plain X-ray of knee region (procedure)': 'Knee XR',
    'Plain X-ray of pelvis (procedure)': 'Pelvis XR',
    'Plain X-ray of wrist region (procedure)': 'Wrist XR',
    'Platelet transfusion (procedure)': 'Plt transfusion',
    'Post anesthesia care management (procedure)': 'PACU',
    'Postoperative care (regime/therapy)': 'Postop care',
    'Postoperative care for dental procedure (regime/therapy)': 'Dental postop care',
    'Postoperative procedure education (procedure)': 'Postop ed',
    'Posttreatment stabilization  orthodontic device (procedure)': 'Ortho stabilization',
    'Pre-discharge assessment (procedure)': 'Pre-d/c assess',
    'Pre-operative chemotherapy (procedure)': 'Neoadj chemo',
    'Pre-surgery testing (procedure)': 'Preop testing',
    'Pregnancy termination care (regime/therapy)': 'TOP care',
    'Premature birth of newborn (finding)': 'Premature birth',
    'Preparation of patient for procedure (regime/therapy)': 'Proc prep',
    'Pretransplant evaluation of kidney recipient (procedure)': 'Kidney txp eval',
    'Professional / ancillary services care (regime/therapy)': 'Ancillary services',
    'Prostatectomy (procedure)': 'Prostatectomy',
    'Psychosocial care (regime/therapy)': 'Psychosocial care',
    'Pulmonary catheterization with Swan-Ganz catheter (procedure)': 'Swan-Ganz',
    'Pulmonary rehabilitation (regime/therapy)': 'Pulm rehab',
    'Radiography of mandible (procedure)': 'Mandible XR',
    'Radiotherapy (procedure)': 'RT',
    'Range of motion testing (procedure)': 'ROM testing',
    'Rectal polypectomy (procedure)': 'Rectal polypectomy',
    'Reexploration procedure (procedure)': 'Reexploration',
    'Referral for echocardiography (procedure)': 'Echo referral',
    'Referral for further care (procedure)': 'Further care referral',
    'Referral for laboratory tests (procedure)': 'Lab referral',
    'Referral to cardiac surgery service (procedure)': 'Cardiac surg referral',
    'Referral to cardiology service (procedure)': 'Cards referral',
    'Referral to dentist (procedure)': 'Dental referral',
    'Referral to home health care service (procedure)': 'HH referral',
    'Referral to hypertension clinic (procedure)': 'HTN clinic referral',
    'Referral to service (procedure)': 'Service referral',
    'Referral to sleep apnea clinic (procedure)': 'Sleep clinic referral',
    'Referral to transplant surgeon (procedure)': 'Txp surg referral',
    'Rehabilitation therapy (regime/therapy)': 'Rehab',
    'Removal of aortic cross clamp (procedure)': 'Cross clamp removal',
    'Removal of endotracheal tube (procedure)': 'ETT removal',
    'Removal of intrauterine contraceptive device (procedure)': 'IUD removal',
    'Removal of subcutaneous contraceptive (procedure)': 'SC contraceptive removal',
    'Removal of subgingival plaque and calculus from all teeth using dental instrument (procedure)': 'Subgingival scaling',
    'Removal of supragingival plaque and calculus from all teeth using dental instrument (procedure)': 'Supragingival scaling',
    'Renal dialysis (procedure)': 'Renal dialysis',
    'Renal disorder medication review (procedure)': 'Renal med review',
    'Replacement of contraceptive intrauterine device (procedure)': 'IUD replacement',
    'Restoration of tooth with coverage of all cusps using dental filling material (procedure)': 'Full cusp coverage',
    'Resuscitation using intravenous fluid (procedure)': 'IV fluid resus',
    'Review of systems (procedure)': 'ROS',
    'Risk assessment (procedure)': 'Risk assess',
    'Rubella screening test (procedure)': 'Rubella screen',
    'Scheduling (procedure)': 'Scheduling',
    'Screening for domestic abuse (procedure)': 'Domestic abuse screen',
    'Screening for drug abuse (procedure)': 'Drug abuse screen',
    'Screening for occult blood in feces (procedure)': 'FOBT',
    'Screening mammography (procedure)': 'Screen mammo',
    'Sentinel lymph node biopsy (procedure)': 'SLNB',
    'Serologic test for Toxoplasma gondii (procedure)': 'Toxo serology',
    'Serum metabolic panel (procedure)': 'Metabolic panel',
    'Simple extraction of tooth (procedure)': 'Simple tooth ext',
    'Simple walk test (procedure)': 'Walk test',
    'Skin test for tuberculosis  Tine test (procedure)': 'TB skin test',
    'Sleep apnea assessment (procedure)': 'Sleep apnea assess',
    'Sleep apnea monitoring with alarm (regime/therapy)': 'Sleep apnea monitor',
    'Social case work (regime/therapy)': 'Social work',
    'Speech and language therapy regime (regime/therapy)': 'Speech therapy',
    'Spirometry (procedure)': 'Spirometry',
    'Sputum examination (procedure)': 'Sputum exam',
    'Sputum microscopy (procedure)': 'Sputum micro',
    'Stair-climbing test (procedure)': 'Stair test',
    'Standard pregnancy test (procedure)': 'Preg test',
    'Sterilization education (procedure)': 'Steril ed',
    'Streptococcus pneumoniae group B antigen assay (procedure)': 'GBS Ag',
    'Subcutaneous immunotherapy (procedure)': 'SCIT',
    'Suicide risk assessment (procedure)': 'Suicide risk assess',
    'Surgical manipulation of joint of knee (procedure)': 'Knee manip',
    'Surgical manipulation of shoulder joint (procedure)': 'Shoulder manip',
    'Suture open wound (procedure)': 'Wound suture',
    'Syphilis infectious titer test (procedure)': 'Syphilis titer',
    'Take oral or dental impression (procedure)': 'Dental impression',
    'Taking patient vital signs (procedure)': 'Vitals',
    'Telemedicine consultation with patient (procedure)': 'Telemed consult',
    'Thoracentesis (procedure)': 'Thoracentesis',
    'Throat culture (procedure)': 'Throat culture',
    'Tooth socket procedure (procedure)': 'Socket procedure',
    'Total replacement of hip (procedure)': 'THA',
    'Transcatheter aortic valve implantation (procedure)': 'TAVI',
    'Transfer to stepdown unit (procedure)': 'Stepdown transfer',
    'Transfusion of fresh frozen plasma (procedure)': 'FFP transfusion',
    'Transfusion of packed red blood cells (procedure)': 'PRBC transfusion',
    'Transplant of kidney (procedure)': 'Kidney txp',
    'Transplant of lung (procedure)': 'Lung txp',
    'Transplantation of kidney regime (regime/therapy)': 'Kidney txp regime',
    'Transthoracic echocardiography (procedure)': 'TTE',
    'Treatment changed (situation)': 'Tx changed',
    'Treatment failure risk education (procedure)': 'Tx failure risk ed',
    'Treatment side effects education (procedure)': 'SE education',
    'Triage: emergency center (procedure)': 'ED triage',
    'Tuberculosis screening (procedure)': 'TB screen',
    'Ultrasonography of abdomen  right upper quadrant and epigastrium (procedure)': 'RUQ US',
    'Ultrasonography of bilateral breasts (procedure)': 'Bilat breast US',
    'Ultrasound scan for fetal viability (procedure)': 'Fetal viability US',
    'Urinalysis with reflex to microscopy and culture (procedure)': 'UA w/reflex',
    'Urine culture (procedure)': 'Urine cx',
    'Urine protein test': 'Urine protein',
    'Urine screening for glucose (procedure)': 'Urine glucose',
    'Urine screening test for diabetes (procedure)': 'Urine DM screen',
    'Urine specimen collection (procedure)': 'Urine collection',
    'Vascular cannula removal (procedure)': 'Vasc cannula removal',
    'Vasectomy (procedure)': 'Vasectomy',
    'Venereal disease screening (procedure)': 'STI screen',
    'Viral hepatitis screening test (procedure)': 'Viral hep screen',
    'Walking exercise test (procedure)': 'Walk test',
    'Weaning from mechanically assisted ventilation (regime/therapy)': 'Vent weaning'
}

can_be_removed_observes = [
    'ALT (Elevated)',  # Redundant with 'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma'
    'AST (Elevated)',  # Redundant with 'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma'
    'Total Bilirubin (Elevated)',  # Redundant with 'Bilirubin.total [Mass/volume] in Serum or Plasma'
    'Alkaline Phosphatase',  # Redundant with 'Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma'
    'Body Temperature',  # Redundant with 'Body temperature' (duplicate with different capitalization)
    'Carbon Dioxide',  # Multiple more specific CO2 measurements are available
    'Chloride',  # Redundant with 'Chloride [Moles/volume] in Serum or Plasma'
    'Creatinine',  # Redundant with 'Creatinine [Mass/volume] in Serum or Plasma'
    'Glucose',  # Redundant with 'Glucose [Mass/volume] in Serum or Plasma'
    'Globulin',  # Redundant with 'Globulin [Mass/volume] in Serum by calculation'
    'Hemoglobin',  # Redundant with 'Hemoglobin [Mass/volume] in Blood'
    'Hematocrit',  # Redundant with 'Hematocrit [Volume Fraction] of Blood'
    'MCV',  # Redundant with 'MCV [Entitic volume] by Automated count'
    'Potassium',  # Redundant with 'Potassium [Moles/volume] in Serum or Plasma'
    'Protein',  # Redundant with 'Protein [Mass/volume] in Serum or Plasma'
    'RBC Distribution Width',  # Redundant with 'Erythrocyte distribution width [Ratio] by Automated count'
    'RBCs',  # Redundant with 'Erythrocytes [#/volume] in Blood by Automated count'
    'Sodium',  # Redundant with 'Sodium [Moles/volume] in Serum or Plasma'
    'Urea Nitrogen',  # Redundant with 'Urea nitrogen [Mass/volume] in Serum or Plasma'
    'WBCs',  # Redundant with 'Leukocytes [#/volume] in Blood by Automated count'
    'Calcium',  # Redundant with 'Calcium [Mass/volume] in Serum or Plasma'
    'Platelet Count',  # Redundant with 'Platelets [#/volume] in Blood by Automated count'
    'Triglycerides',  # Less specific measurement compared to lipid panel components
    'Low Density Lipoprotein Cholesterol',  # Can be calculated from other lipid panel results
    'Albumin'  # Redundant with 'Albumin [Mass/volume] in Serum or Plasma'
]