FROM python:3.13.3-bullseye

RUN pip install intersystems-irispython
RUN pip install https://github.com/intersystems-community/intersystems-irispython/releases/download/3.9.2/intersystems_iris-3.9.2-py3-none-any.whl
RUN pip install pandas

#WORKDIR /home/python/work
 
#CMD ["python", "test_conect.py"]
